In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns
import statsmodels as sm

In [4]:
%pwd

'/Volumes/Transcend/anubhav transcend/model-preparation/Machine-Learning-in-Python/path_of_ML/Pandas/Book'

In [5]:
b = "bat"

In [9]:
def add_numbers(a, b): 
    """
            Add two numbers together
    Returns
    -------
    the_sum : type of arguments """
    return a+b

In [10]:
add_numbers?

In [11]:
np.load?

In [12]:
data = np.random.randn(2,3)

In [13]:
data

array([[ 0.19927292, -0.83039773,  0.42689525],
       [-1.57096627, -1.22328541, -1.27196368]])

In [14]:
data * 10

array([[  1.99272924,  -8.30397731,   4.26895248],
       [-15.70966273, -12.23285413, -12.7196368 ]])

In [15]:
data + data

array([[ 0.39854585, -1.66079546,  0.8537905 ],
       [-3.14193255, -2.44657083, -2.54392736]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data = [1,2,3,4,3,4,5,5]

In [19]:
arr1 = np.array(data)

In [20]:
arr1

array([1, 2, 3, 4, 3, 4, 5, 5])

In [21]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr2.dtype

dtype('int64')

In [31]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr1 = np.array([1, 2, 3], dtype=np.float64)