# Mathematics

In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3,5])

In [3]:
a += 2

In [5]:
a - 2

array([1, 2, 3])

In [6]:
a * 2

array([ 6,  8, 10])

In [7]:
a / 2

array([1.5, 2. , 2.5])

In [11]:
b = np.array([1,2,3,4])

In [15]:
a+b

array([2, 4, 6, 9])

In [16]:
a ** 2

array([ 1,  4,  9, 25], dtype=int32)

In [17]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427])

## Linear Algebra

In [19]:
a = np.ones((2,3))

In [20]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
b = np.full((3,2), 2)

In [22]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [25]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [26]:
c = np.identity(3)

In [27]:
np.linalg.det(c)

1.0

In [28]:
b = np.full((3,3), 2)

In [29]:
np.linalg.det(b)

0.0

## Statistics

In [30]:
stats = np.array([[1,2,3],[4,5,6]])

In [31]:
np.min(stats, axis=0)

array([1, 2, 3])

In [32]:
np.max(stats)

6

In [33]:
np.min(stats)

1

In [36]:
np.min(stats,axis=1)

array([1, 4])