## Load data from file

In [2]:
import numpy as np

In [4]:
data = np.genfromtxt("input.txt", delimiter=",")

In [5]:
data.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced Indexing

In [8]:
data[data > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
a[[1,2,8]]

array([2, 3, 9])

In [15]:
np.all(data > 5 , axis=1)

array([False, False, False])

In [17]:
((data > 5) & (data < 50))

array([[False,  True,  True,  True, False, False, False, False,  True,
         True,  True,  True, False, False, False, False, False, False],
       [False,  True,  True,  True, False, False, False, False,  True,
        False, False, False, False,  True,  True, False,  True,  True],
       [False,  True,  True,  True, False,  True, False, False, False,
        False, False, False,  True,  True,  True, False, False, False]])

In [18]:
(~((data > 5) & (data < 50)))

array([[ True, False, False, False,  True,  True,  True,  True, False,
        False, False, False,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True,  True,  True, False,
         True,  True,  True,  True, False, False,  True, False, False],
       [ True, False, False, False,  True, False,  True,  True,  True,
         True,  True,  True, False, False, False,  True,  True,  True]])

In [19]:
a[2:4, 0:2]

IndexError: too many indices for array

In [22]:
a = np.genfromtxt("data.txt", delimiter=",")

In [23]:
a[2:4, 0:2]

array([[11., 12.],
       [16., 17.]])

In [24]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2.,  8., 14., 20.])

In [35]:
a[[0,4,5],3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])