In [2]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [3]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [7]:
#specific row, column
a[1,2]

array([10, 11, 12, 13, 14])

In [8]:
#specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#specific column
a[:,2]

array([ 3, 10])

In [13]:
a[0, 1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5] = 79

In [15]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 79, 14]])

In [16]:
a[:,2] = [74,12]

In [17]:
a

array([[ 1,  2, 74,  4,  5,  6,  7],
       [ 8,  9, 12, 11, 12, 79, 14]])

In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
b[0,1,1]

4

In [23]:
b[:,1,:] = [[9,9],[8,8]]

In [24]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])