In [2]:
import numpy as np

In [25]:
a = np.array([3,6,9], dtype="int16")
print(a)

[3 6 9]


In [17]:
b = np.array([[9.0,8.0,7.0],[2.0,4.0,5.0]],dtype="int")
print(b)

[[9 8 7]
 [2 4 5]]


In [18]:
# Dimension
b.ndim

2

In [19]:
# shape
b.shape

(2, 3)

In [20]:
# Type
b.dtype

dtype('int32')

In [26]:
# Item Size
a.itemsize

2

In [27]:
a.size * a.itemsize

6

In [29]:
# Total size
a.nbytes

6