# Initilize the diffferent types of array

In [2]:
import numpy as np

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((2,2), dtype="int32")

array([[1, 1],
       [1, 1]])

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.full((2,2), 4,dtype="float32")

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [17]:
a = np.array([3,6,9], dtype="int16")

In [20]:
np.full_like(a,6)

array([6, 6, 6], dtype=int16)

In [25]:
np.random.rand(4,2)

array([[0.95266535, 0.92435267],
       [0.62878232, 0.44527269],
       [0.06784791, 0.73611973],
       [0.58979431, 0.89697659]])

In [26]:
np.random.random_sample(a.shape)

array([0.88905691, 0.24933884, 0.45213929])

In [30]:
np.random.randint(4,8, size=(3,3))

array([[5, 6, 7],
       [4, 6, 7],
       [4, 4, 4]])

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr = np.array([1,2,3])

In [33]:
r1 = np.repeat(arr,2)

In [34]:
r1

array([1, 1, 2, 2, 3, 3])

In [39]:
arr = np.array([[1,2,3]])
r2 = np.repeat(arr,2,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3]])

In [40]:
r3 = np.repeat(arr,2,axis=1)
r3

array([[1, 1, 2, 2, 3, 3]])

In [41]:
output = np.ones((5,5))

In [42]:
z = np.zeros((3,3))

In [43]:
z[1,1] = 9

In [45]:
output[1:4,1:4] = z

In [46]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be carefull when copying arrays!!!

In [48]:
a = np.array([1,2,3])

In [49]:
b = a

In [50]:
b[0] = 100

In [51]:
b

array([100,   2,   3])