# Reorganizing Array

In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3],[4,5,6]])

In [4]:
after = before.reshape(6,1)

In [5]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [6]:
before.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Vertically stacking vectors

In [9]:
v1 = np.array([1,2,3,4,5])

In [10]:
v2 = np.array([5,6,7,8,9])

In [12]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

## Horizontal stack

In [14]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [16]:
np.hstack([h1,h2,h1])

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])